#!/bin/sh
REPOS="https://raw.githubusercontent.com/Annnjayy/ssh/main/"
ns_domain_cloudflare() {
	DOMAIN="makhlukvpn.my.id"
	DOMAIN_PATH=$(cat /etc/xray/domain)
	SUB=$(tr </dev/urandom -dc 0-9 | head -c4)
	NS_DOMAIN=slowdns${SUB}.${DOMAIN}
	CF_ID=makhlukvpn@gmail.com
        CF_KEY=1e1fd5209818f9492309a6c60b94e1df4340f
	set -euo pipefail
	IP=$(wget -qO- ipinfo.io/ip)
	echo "Updating DNS NS for ${NS_DOMAIN}..."
	ZONE=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN}&status=active" \
		-H "X-Auth-Email: ${CF_ID}" \
		-H "X-Auth-Key: ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

	RECORD=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${NS_DOMAIN}" \
		-H "X-Auth-Email: ${CF_ID}" \
		-H "X-Auth-Key: ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

	if [[ "${#RECORD}" -le 10 ]]; then
		RECORD=$(
			curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
			-H "X-Auth-Email: ${CF_ID}" \
			-H "X-Auth-Key: ${CF_KEY}" \
			-H "Content-Type: application/json" \
			--data '{"type":"NS","name":"'${NS_DOMAIN}'","content":"'${DOMAIN_PATH}'","proxied":false}' | jq -r .result.id
		)
	fi

	RESULT=$(
		curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
		-H "X-Auth-Email: ${CF_ID}" \
		-H "X-Auth-Key: ${CF_KEY}" \
		-H "Content-Type: application/json" \
		--data '{"type":"NS","name":"'${NS_DOMAIN}'","content":"'${DOMAIN_PATH}'","proxied":false}'
	)
	echo $NS_DOMAIN >/etc/xray/dns
    echo -e "Done Record NSDomain For VPS"
    sleep 2
}

setup_dnstt() {
	cd
	wget -O /etc/slowdns/dnstt-server "${REPOS}slowdns/dnstt-server" >/dev/null 2>&1
	chmod +x /etc/slowdns/dnstt-server >/dev/null 2>&1
	wget -O /etc/slowdns/dnstt-client "${REPOS}slowdns/dnstt-client" >/dev/null 2>&1
	chmod +x /etc/slowdns/dnstt-client >/dev/null 2>&1
	/etc/slowdns/dnstt-server -gen-key -privkey-file /etc/slowdns/server.key -pubkey-file /etc/slowdns/server.pub
	chmod +x /etc/slowdns/*
	wget -O /etc/systemd/system/client.service "${REPOS}slowdns/client" >/dev/null 2>&1
	wget -O /etc/systemd/system/server.service "${REPOS}slowdns/server" >/dev/null 2>&1
	sed -i "s/xxxx/$NS_DOMAIN/g" /etc/systemd/system/client.service
	sed -i "s/xxxx/$NS_DOMAIN/g" /etc/systemd/system/server.service
    sleep 2
}
ns_domain_cloudflare
setup_dnstt
