#!/bin/bash
REPO="https://raw.githubusercontent.com/Annnjayy/ssh/main/"

    echo " ----->> Downloading Toll UdpCustom........"
    sleep 2
    wget -q --show-progress --load-cookies /tmp/cookies.txt "${REPO}bin/custom" -O /usr/sbin/custom >/dev/null 2>&1
    rm -rf /tmp/cookies.txt
    chmod +x /usr/sbin/custom
    echo " ----->> Please Waiting Proses Downloading Default Config UdpCustom........"
    sleep 2
    wget -q --show-progress --load-cookies /tmp/cookies.txt "${REPO}bin/config.json" -O /root/.config/udp/config.json >/dev/null 2>&1
    rm -rf /tmp/cookies.txt
    chmod 644 /root/.config/udp/config.json
    sleep 2

if [ -z "$1" ]; then
cat <<EOF > /etc/systemd/system/custom.service
[Unit]
Description=UDP Custom by MakhlukVpn

[Service]
User=root
Type=simple
ExecStart=/usr/sbin/custom server
WorkingDirectory=/root/.config/udp/
Restart=always
RestartSec=2s

[Install]
WantedBy=default.target
EOF
else
cat <<EOF > /etc/systemd/system/custom.service
[Unit]
Description=UDP Custom

[Service]
User=root
Type=simple
ExecStart=/usr/sbin/custom server -exclude $1
WorkingDirectory=/root/.config/udp/
Restart=always
RestartSec=2s

[Install]
WantedBy=default.target
EOF
fi

echo start service custom
systemctl start custom
echo enable service custom
systemctl enable custom 
echo ""
sleep 0,5
clear
